pekko {
  actor {
    provider = "remote"
  }
  remote {
    artery {
      transport = tcp
      canonical.hostname = "0.0.0.0"
      canonical.port = 2552
      bind.hostname = "0.0.0.0"
      bind.port = 2552
    }
    log-sent-messages = on
    log-received-messages = on
  }
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
}
at-least-once-delivery {
    redeliver-interval = 20000
    redelivery-burst-limit = 100
    warn-after-number-of-unconfirmed-attempts = 6
}
pekko.persistence.journal.plugin = "pekko.persistence.journal.inmem"
# Absolute path to the default snapshot store plugin configuration entry.
pekko.persistence.snapshot-store.plugin = "pekko.persistence.snapshot-store.local"

