package test;


import cn.hutool.json.JSONUtil;
import com.datasophon.dao.entity.ClusterHostDO;
import com.datasophon.k8s.util.KubeUtil;
import io.fabric8.kubernetes.api.model.Node;
import io.fabric8.kubernetes.api.model.NodeList;
import io.fabric8.kubernetes.client.KubernetesClient;
import org.junit.Test;

import java.util.List;

public class TestKube {

    private final static String KUBE_CONFIG =
            "apiVersion: v1\n" +
                "clusters:\n" +
                "- cluster:\n" +
                "    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvRENDQW9pZ0F3SUJBZ0lVVDZVK2x0K3U4TC9TRlIyUklWcHh2V3duWW9vd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1p6RUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0ZOb1lXNW5TR0ZwTVJFd0R3WURWUVFIRXdoVAphR0Z1WjBoaGFURU1NQW9HQTFVRUNoTURhemh6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4RXpBUkJnTlZCQU1UCkNtdDFZbVZ5Ym1WMFpYTXdJQmNOTWpRd056RXhNRGcwTWpBd1doZ1BNakV5TkRBM01USXdPRFF5TURCYU1HY3gKQ3pBSkJnTlZCQVlUQWtOT01SRXdEd1lEVlFRSUV3aFRhR0Z1WjBoaGFURVJNQThHQTFVRUJ4TUlVMmhoYm1kSQpZV2t4RERBS0JnTlZCQW9UQTJzNGN6RVBNQTBHQTFVRUN4TUdVM2x6ZEdWdE1STXdFUVlEVlFRREV3cHJkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE1b0ZCSlMxSTUwbFYKTkdHeWIrQU83QjQzV0hzcGlwamJCblFLTU92V2hheFd0cEw3V1lDdDhCOERLTmk3NWZRQjVYUEhPaGxEVldMVAp3eUdkOXUvd2lYSGNHVEN1SmJ6dmZwWExqMWN6ai9uNDc0cGVWRnhGRnV4TGRTbjk1WmpLQytlMDJHWU5jQ3BPCjQ5WmIvekFCbTFlNWdDbTI2R0J2NFFQeXo5TWQrK29nY3pSTENTWkN1Z1l0emF4d2dMWFdlL1FhTUE3Zy84Z04KRTBQRDFEb09Ya3l4WnZ0dXNnWGtlVXB4QXdKL0hQbjhwYXJtQ2c2aUZ5d3lYK0d4ajVaQTgycGhKYzZQcHVldgo1UEk3THlHVzErTjBIL2NwNWUzbkxNRjBRUENJYzk3RFZQSDZqMERONXRDZENWelZCN1M2ZmhzOXcvM21QK240Ck1UM3Vldk9QTFFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVUYzZVlyQytXOUxMOGdOemtLZFMxMnBzTjNxb3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUVyb0IyS2svMnVtSkN0dUp4NlJFZkppeHJ1R2l3eEQ5eWNkaVM2UUdTUCtXM0dua05aVFpaWmNFcVJCCkZlYmZRUEc4OVhLdDNEdVRPUkFReVZrUjdCRGZGSFFGM1pUeEdhemdVcGc1UmVpZ2xOdm9BMEM4dm9MdFB6VGMKekx2bktFUm5wSEVuNjZZU0grcjdmU0R3a1g5V2J1OGR2by9tMkQ1cU1oTEtEaGVwMC9sWDlKT3hPOXJlZUlQcgpzMXh2VGJNQlVSMkVHd0dDWkE3T2xXeDZSbi80bXRGaTZoNENVNDVxUE4rWXlmYWJvMEpxdkpGVGswSDA5dGRBCmovSWxFUzVCbmtJZVVsdXNVK1htNVVXQndUMTBwZm5OSmp2YU1EL0lXaDdCK3FoU3Yvd1Urb0t5Q0dJRWhBR0gKczhWK3NwZEY1b2hkZXk5VmIxbCtvSzhrWmlrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==\n" +
                "    server: https://192.168.1.203:6443\n" +
                "  name: kubernetes\n" +
                "contexts:\n" +
                "- context:\n" +
                "    cluster: kubernetes\n" +
                "    user: admin\n" +
                "  name: kubernetes\n" +
                "current-context: kubernetes\n" +
                "kind: Config\n" +
                "preferences: {}\n" +
                "users:\n" +
                "- name: admin\n" +
                "  user:\n" +
                "    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ0ekNDQXN1Z0F3SUJBZ0lVWm4xTyszTjJSMzA3Vk12ejZkTVFXVWJxbkZNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1p6RUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0ZOb1lXNW5TR0ZwTVJFd0R3WURWUVFIRXdoVAphR0Z1WjBoaGFURU1NQW9HQTFVRUNoTURhemh6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4RXpBUkJnTlZCQU1UCkNtdDFZbVZ5Ym1WMFpYTXdJQmNOTWpRd056RXhNVEF3T0RBd1doZ1BNakV5TkRBM01USXhNREE0TURCYU1HMHgKQ3pBSkJnTlZCQVlUQWtOT01SRXdEd1lEVlFRSUV3aFRhR0Z1WjBoaGFURVJNQThHQTFVRUJ4TUlVMmhoYm1kSQpZV2t4RnpBVkJnTlZCQW9URG5ONWMzUmxiVHB0WVhOMFpYSnpNUTh3RFFZRFZRUUxFd1pUZVhOMFpXMHhEakFNCkJnTlZCQU1UQldGa2JXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW5HQTcKU2VqeEU0OTFEVnFNVWVOUTE1LzNJdHE3WS9HUmt4S0hkUjA1WkhVYWxBQWc5SXdvTmlaTWV5c0hDNUlRMllxMgpvYUo5UHNHcnh2UnNYb09QVWhnazBxSFdmV0RkZDh6MlpiNEo5Wmw5eUs2NHdNdGEwWlR4aS9YdEtiOURmRG80CldCdnhVeWh2VC8yQVBDTG01YzQyZHBpNTUvR1J6am9PUVJGa2xBdEN2aHRSbDFkRjZLRlRlZTZFQm5aNGNlZ1gKOHlvaGNqUjFkWlpwc2J1WW1xSGdxZ0MraGMyVDgwclpSdmp2U21lZE14YlFFZUNYNGFJazhUSUwzaWtNK09lTQpiS1A1bXVkRWpWTUFXRmJMekJpQUFjeHpkYWdhZUUyeVkzWHhLTVhhUkVrNkgxOHAxZ0JHSDIwOW9OcUVUR2kxCjNVMUIyREJOVlQ2SDd1MHhVd0lEQVFBQm8zOHdmVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXcKRkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkFvYQpqZEZPb1hFdkdjK1lROWtCbnBKcEVZRkJNQjhHQTFVZEl3UVlNQmFBRkJkM21Ld3ZsdlN5L0lEYzVDblV0ZHFiCkRkNnFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUMvdWo1a3B6S0lJWG5neHFMRXBUWmdsN2M2T3djUVhKNnkKZ3FNc1VJNW9sZWFjZ1FEUFBBZ1FyUGZZVWxsWGhEd2pERUFRWFl4NThCUG9tVVNGNmxBWmk0TVUzRnUrbzVmUAo5Zkh2aWxLRjRHWVNXMU9uU2pGNWNZeUw0OWxyUzdlVU04bCtnWkg1QjdTd1dzdTM4Q09sTWE2T2VlUlYwdmVlCitvSDdtMHJFWnlJRTB0aEVwZlJDM2xDc3hCQVBDWGhNU2RXcGVobjhpNGdnMjNaaEg4NjhqUVFxVm1BaVVLdnoKN1ZpR09lSGtESmxOY0R1WkF0dHo4d3lEZG1PK2FOeU5abHZIT29SRUNtSHNWOU9XdVNUMlJEeVZ5N01TbTJ2UApPei9VbWNGTy9hMXRLRkVEaWo0Y3F0clNhN2p1cWR3NEtXSWVwK1B3Z1hiRVFhQU1sOUpSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K\n" +
                "    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbkdBN1NlanhFNDkxRFZxTVVlTlExNS8zSXRxN1kvR1JreEtIZFIwNVpIVWFsQUFnCjlJd29OaVpNZXlzSEM1SVEyWXEyb2FKOVBzR3J4dlJzWG9PUFVoZ2swcUhXZldEZGQ4ejJaYjRKOVpsOXlLNjQKd010YTBaVHhpL1h0S2I5RGZEbzRXQnZ4VXlodlQvMkFQQ0xtNWM0MmRwaTU1L0dSempvT1FSRmtsQXRDdmh0UgpsMWRGNktGVGVlNkVCblo0Y2VnWDh5b2hjalIxZFpacHNidVltcUhncWdDK2hjMlQ4MHJaUnZqdlNtZWRNeGJRCkVlQ1g0YUlrOFRJTDNpa00rT2VNYktQNW11ZEVqVk1BV0ZiTHpCaUFBY3h6ZGFnYWVFMnlZM1h4S01YYVJFazYKSDE4cDFnQkdIMjA5b05xRVRHaTEzVTFCMkRCTlZUNkg3dTB4VXdJREFRQUJBb0lCQVFDQTYvbVZhcjN1Z1hSZwphUW1Nclp0RjJqVTNBQnhFUHJIbERmNnRlRVdMNDl2Z3J1WjhsMXpEbi9tb0JnWk43TU9GaG80aFhrUmh5K3dpCkgvdUVSSFNSbXlRb241S2xWWW5oTGhMcU9LNGZWTWRWLzI2RVRHTjRySklqOE1IeGpDVklNdnVtOElxYUk1ajUKMnFheGJaanRWNENoY0RLODNmVjJqM2lXL283c1diNW0rR3laZzUxa3VOVCtVRHZyZ1Rlc2Z6MjZXdXRNcEpGUwpqSGFKcklUNWhxUUE2ckdUWkdOQjF5QVZTaWdLTmdEeHllRk4rblhkVHQ3R3k3NTVJVU1YMnEyWHB5R3JyODZ5Ckxaei9WNHRwQzh4Y0hRMzdCRHJlZVNqcDRmSy9MR3JKaUxGNXdXUVlXTkdNb2IrVTBkMlFJM1p6ZWl1aEFyVEoKSWZEL3Q3ejVBb0dCQU1sQXhheThoNGtxZ0F3UnVyVGRNRVFxRUh4R0kvZzhTcHFJelg0aGpvMGZMOGN1NGNkYQpZN1h2TnpWcHhwMHdWbXZ4c0tCWGh0VUp4Z1F4S2pEQnFldk1iQVJ6T0NPdlI4ZjFOc3ZrUzB4T0lNUHI4U1NWCjVBODRXdmxuclBnSzcxcTJrWW8xZUlZVTNCTXliR2pRR1lvcldrdWtYRkxHZlZub3VmRnBOUjF2QW9HQkFNYnEKT1h6cDI4RGFqQzMwSmZIVjFrZ25PeGRkSTFJRmNIN2tvSUpabk5YYmFWRkY4cFVHbTloMlBnUnVzelpYQzVkaApOejhWbzZIZ2pQZ3JxVzQ4cDZFT24rY2ZKWXVwaWlBNS9oOVRvU251R2ZsMlRVYW9kQUZPWEc1RS9QWGUxTFpUClNUWHZtZlhTclY2dkcrd2NEc3dZTVB4SUcvNFVEVjlLV25UMXRvQmRBb0dBQ01Sb21DRFNhcmhPUWJoWUFOOE4KNWpwSzQ0OE9yQmE4VFVVZVpwdEJvWVkxUjZFVU51SUtLL2ZTMk9IVnhDMUI1b3Z0M041VFFsNmRvTHNma21ZdApaOWRNOFZpdm5tWlpZeTJjaUg5V2hHbDI1ZklXWERpbmFiNVR3RCt5K2s5SHBCVUYvQlplUE1FVjRVUTJFczdWCi9mM3JmaFlYNjRjNEdMMlp0Qm1ZTmNNQ2dZQnMxelRsbU1EWjRidmFXVUY1OWx2dDF5bUtPemhjWlFXTktXUjYKYnJaV2ZsdytVRnZRRjNHbkcrd0xXTmRPNElwREpycW9GaHNYTkZ0dVg5V3hzQmE1RmR1QkI1WHZ1YkVPdVN6SAp6MmJjSHFDdjAzK3RMZmRyejRqYi9YdTh2VlQrL3N1TWE3Sit3K3lCWnFlTXBqMmloNG9tUVA2d0pDQzlCMTQvCnFVTlhNUUtCZ0I0eS9MaEFWUWtqcTJRcnoySHU4Wm9nL0t4bXF5cU14UDY4di9NMHB3ZDhoRkhVKzVmaURoYzQKMmsweEd6NjVVdkNsTkZmd3RBYjZmRUs5ZUdlakpnSmFxeStYOVBGRkwrbW5yUFZ0WENhWHVtL0oySEdIc0JuWgpURjdXSFc0UldWeEs0TWRXMzNxVWthYUxPZldMbitTS291SVdnZmJSZ3RBWjJGMTlaN1JxCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==\n";

    public static KubernetesClient getClient() {
        KubeUtil kubeUtil = new KubeUtil();
        return kubeUtil.getKubeClientByConfig(KUBE_CONFIG);
    }

    @Test
    public void test() {
        KubernetesClient client = getClient();
        NodeList list = client.nodes().list();
        List<Node> items = list.getItems();
        System.out.println(JSONUtil.toJsonStr(items));
    }

    @Test
    public void testNodeList() {
        KubeUtil kubeUtil = new KubeUtil();
        List<ClusterHostDO> list = kubeUtil.getHostListByConfig(1);
        System.out.println(JSONUtil.toJsonStr(list));
    }
}
