plugin.id=system-info
plugin.class=com.datasophon.plugins.systeminfo.SystemInfoCollectorPlugin
plugin.version=3.0.0
plugin.provider=DataSophon
plugin.dependencies=
plugin.requires=*
plugin.license=Apache-2.0

