# Production stage
FROM harbor.norintech.com/bdp/nginx:stable-alpine

# 设置时区
ENV TZ=Asia/Shanghai

WORKDIR /app

# 复制构建文件到/app目录
COPY datasophon-ui/dist /app/

# 复制nginx配置
COPY deploy/docker/nginx.conf /etc/nginx/conf.d/default.conf

# 暴露端口
EXPOSE 80

# 健康检查
HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost/ddh/ || exit 1

CMD ["nginx", "-g", "daemon off;"] 