plugin.id=ssh-connector
plugin.class=com.datasophon.plugins.impl.ssh.SshConnectorPluginMain
plugin.version=1.0.0
plugin.provider=DataSophon Team
plugin.dependencies=
plugin.description=High-performance SSH connection pool based on Apache Commons Pool2
plugin.license=Apache License 2.0
plugin.requires=*