FROM 192.168.5.200:5000/bdp/openjdk:8

# 创建工作目录并复制必要的文件
RUN mkdir -p /opt/datasophon/datasophon-worker /opt/datasophon/DDP/packages
COPY ./bin/ /opt/datasophon/datasophon-worker/bin/
COPY ./conf/ /opt/datasophon/datasophon-worker/conf/
COPY ./lib/ /opt/datasophon/datasophon-worker/lib/
COPY ./jmx/ /opt/datasophon/datasophon-worker/jmx/
COPY ./node/ /opt/datasophon/datasophon-worker/node/
COPY ./script/ /opt/datasophon/datasophon-worker/script/

# 设置工作目录
WORKDIR /opt/datasophon/datasophon-worker

# 设置环境变量
ENV TZ=Asia/Shanghai \
    DDH_HOME=/opt/datasophon/datasophon-worker \
    JAVA_OPTS="-server -Xms1G -Xmx1G -Xmn512m" \
    LOG_FILE="-Dlogging.config=classpath:logback.xml -Dspring.profiles.active=worker" \
    JMX="-javaagent:/opt/datasophon/datasophon-worker/jmx/jmx_prometheus_javaagent-0.16.1.jar=8585:/opt/datasophon/datasophon-worker/jmx/jmx_exporter_config.yaml" \
    CLASS=com.datasophon.worker.WorkerApplicationServer \
    CLASSPATH=/opt/datasophon/datasophon-worker/conf:/opt/datasophon/datasophon-worker/lib/*

# 暴露端口
EXPOSE 8001
EXPOSE 8585
EXPOSE 2552

# 设置入口点
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS $LOG_FILE $JMX -classpath $CLASSPATH $CLASS"]
