TEZ=$IMAGE_REGISTRY/bdp/tez:0.10.2
MINIO=$IMAGE_REGISTRY/bdp/minio:20240613
KYUUBI=$IMAGE_REGISTRY/bdp/kyuubi:1.7.3
DS=$IMAGE_REGISTRY/bdp/ds:3.1.8
HUE=$IMAGE_REGISTRY/bdp/hue:4.11.0
HDFS=$IMAGE_REGISTRY/bdp/hadoop:3.3.3
RANGER=$IMAGE_REGISTRY/bdp/ranger:2.1.0
OPENLDAP=$IMAGE_REGISTRY/bdp/openldap:2.4.44
KAFKA=$IMAGE_REGISTRY/bdp/kafka:2.4.1
ELASTICSEARCH=$IMAGE_REGISTRY/bdp/elasticsearch:7.16.2
HBASE=$IMAGE_REGISTRY/bdp/hbase:2.2.7
ALLUXIO=$IMAGE_REGISTRY/bdp/alluxio:2.9.3
KERBEROS=$IMAGE_REGISTRY/bdp/kerberos:1.15.1
PUSHGATEWAY=$IMAGE_REGISTRY/bdp/pushgateway:1.7.0
GRAFANA=$IMAGE_REGISTRY/bdp/grafana:9.1.6
HIVE=$IMAGE_REGISTRY/bdp/hive:3.1.0
POSTGRESQL=$IMAGE_REGISTRY/bdp/postgresql:16.1
FLUME=$IMAGE_REGISTRY/bdp/flume:1.11.0
NEO4J=$IMAGE_REGISTRY/bdp/neo4j:5.16.0
TRINO=$IMAGE_REGISTRY/bdp/trino:367
ALERTMANAGER=$IMAGE_REGISTRY/bdp/alertmanager:0.23.0
ZOOKEEPER=$IMAGE_REGISTRY/bdp/zookeeper:3.5.10
REDIS=$IMAGE_REGISTRY/bdp/redis:7.2.3
CLICKHOUSE=$IMAGE_REGISTRY/bdp/clickhouse:23.9.1.1854
PRESTO=$IMAGE_REGISTRY/bdp/presto:0.287
STREAMPARK=$IMAGE_REGISTRY/bdp/streampark:2.1.1
SPARK3=$IMAGE_REGISTRY/bdp/spark3:3.2.2
ICEBERG=$IMAGE_REGISTRY/bdp/iceberg:1.4.0
STARROCKS=$IMAGE_REGISTRY/bdp/starrocks:3.3.2
DORIS=$IMAGE_REGISTRY/bdp/doris:1.2.6
FLINK=$IMAGE_REGISTRY/bdp/flink:1.16.2
SEATUNNEL=$IMAGE_REGISTRY/bdp/seatunnel:2.3.3
ZEPPELIN=$IMAGE_REGISTRY/bdp/zeppelin:0.10.1
HUDI=$IMAGE_REGISTRY/bdp/hudi:0.13.0
PROMETHEUS=$IMAGE_REGISTRY/bdp/prometheus:2.17.2
YARN=$IMAGE_REGISTRY/bdp/hadoop:3.3.3
NOAHJOB=$IMAGE_REGISTRY/bdp/noahjob:3.0.0
NOAHSYNC=$IMAGE_REGISTRY/bdp/noahsync:2.3.5
NEBULAGRAPH=$IMAGE_REGISTRY/bdp/nebulagraph:3.6.0
REDISSENTINEL=$IMAGE_REGISTRY/bdp/redissentinel:7.4.0
LOGSTASH=$IMAGE_REGISTRY/bdp/logstash:7.16.2
KIBANA=$IMAGE_REGISTRY/bdp/kibana:7.16.2
JUICEFS=$IMAGE_REGISTRY/bdp/juicefs:1.2.2
BUSYBOX=$IMAGE_REGISTRY/bdp/busybox:1.28