plugin.id=host-validation
plugin.class=com.datasophon.plugins.hostvalidation.HostValidationPlugin
plugin.version=3.0.0
plugin.provider=DataSophon
plugin.dependencies=
plugin.requires=*
plugin.license=Apache-2.0

