plugin.id=host-repair
plugin.class=com.datasophon.plugins.hostrepair.HostRepairPlugin
plugin.version=3.0.0
plugin.provider=DataSophon
plugin.dependencies=
plugin.requires=*
plugin.license=Apache-2.0

