# this file has the highest priority, if val is not blank, then will replace the config

# datasource config
# mysql
datasource.driver=com.mysql.cj.jdbc.Driver
datasource.url=jdbc:mysql://192.168.20.60:3306/ddp?&useUnicode=true&characterEncoding=utf-8
datasource.username=root
datasource.password=123456
# 达梦
# datasource.driver=dm.jdbc.driver.DmDriver
# datasource.url=jdbc:dm://192.168.4.120:5236/DATASOPHON?rewriteBatchedStatements=true&useServerPrepStmts=false&allowMultiQueries=true
# datasource.username=DATASOPHON
# datasource.password=DATASOPHON

# server
server.port=8081
server.address=0.0.0.0

datasophon.migration.enable=true

sso.active=false
sso.auth-url=https://192.168.5.184:10000/index.html
sso.server-url=https://192.168.5.174:10000/sso-server/
sso.redis-nodes=192.168.5.160:6379,192.168.5.161:6379,192.168.5.162:6379
sso.redis-password=zb@123
sso.public-key=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCerqMJBTLxl/5ozlNeysw/SwuOPiqTTKd/j1MCm/2Zj/79VJ0FFvhKtOzOBYhoIu/QtlJPG2Lxrw3vNMksyqMiZ8Wca6a1/DgTicD/t8uTzx6buvfIR7GwccK1a/7u1mL2ZqddTIlmkvx/0IiAxXV2pDnQn1QS400O/xKr6RdXywIDAQAB


IMAGE_REGISTRY=harbor.norintech.com
language=chinese
install.path=/opt/datasophon
yaml.path=/project-code/noah-bigdata-platform
masterHost=master01
masterWebPort=8081
frameCode=DDP-1.2.1
clusterId=1
rows=200
times=20
timeOutPeriodOne=1
timeOutPeriodTwo=2
HADOOP_HOME=/opt/datasophon/hadoop-3.3.3
id_rsa=/.ssh/id_rsa