# this file has the highest priority, if val is not blank, then will replace the config

# datasource config
datasource.ip=192.168.1.54
datasource.port=3306
datasource.database=datasophon
datasource.username=root
datasource.password=123456

# server
server.port=8081
server.address=0.0.0.0
