{
 "title": "Kerberos",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "kdc_role", "label": "KDC角色", "query": "Krb5Kdc" },
   { "name": "kadmin_role", "label": "KAdmin角色", "query": "KAdmin" },
   { "name": "client_role", "label": "Krb5Client角色", "query": "Krb5Client" },
   {
    "name": "available_roles",
    "label": "可用角色",
    "query": {
     "query": "label_values(service_role_instance_count, role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Krb5Kdc在线实例",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(service_role_instance_count{role=\"$kdc_role\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "KAdmin在线实例",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(service_role_instance_count{role=\"$kadmin_role\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Krb5Client数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(service_role_instance_count{role=\"$client_role\"}) or vector(0)"
    }
   ]
  }
 ]
}