apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  hostNetwork: false  # 使用宿主机的网络
  nodeSelector:
    kubernetes.io/hostname: 
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    effect: "NoSchedule"
  containers:
  - name: mysql
    image: harbor.norintech.com/bdp/mysql:5.7
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "$MYSQL_ROOT_PASSWORD"
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql  # 挂载本地数据目录
    - name: mysql-config
      mountPath: /etc/my.cnf  # 挂载本地配置文件
  volumes:
  - name: mysql-data
    hostPath:
      path: /var/lib/mysql  # 挂载宿主机的 /var/lib/mysql
  - name: mysql-config
    hostPath:
      path: /data/mysql/my.cnf  # 挂载宿主机的 /data/mysql/my.cnf

