<#if emailEnable == 'true'>
  # 全局配置
global:
  ## 在没有报警的情况下声明为已解决的时间
  resolve_timeout: 5m
  ## ===配置邮箱===
  ## 配置邮箱 SMTP 服务器地址和端口
  smtp_smarthost: ${smtpSmarthost}
  ## 配置发件人邮箱
  smtp_from: ${smtpFrom}
  ## 配置发件人邮箱账户
  smtp_auth_username: ${smtpAuthUsername}
  ## 配置发件人邮箱密码 (这里指的是邮箱授权码，不是登录密码)
  smtp_auth_password: ${smtpAuthPassword}
  ## 配置是否使用 TLS 加密
  smtp_require_tls: false
</#if>

route:
  group_by: ['alertname','email_to']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'web.hook'
  routes:
    - receiver: "web.hook"
      continue: true
<#if emailEnable == 'true'>
  <#list itemList as item>
    - receiver: ${item.name}
    - match_re:
        noticeGroupId: ${item.name}
  </#list>
</#if>
receivers:
- name: 'web.hook'
  webhook_configs:
  - send_resolved: true
    url: 'http://${apiUrl}/ddh/cluster/alert/history/save'

<#if emailEnable == 'true'>
  <#list itemList as item>
- name:  ${item.name}
  email_configs:
    - to: ${item.value}
  </#list>
</#if>

# 抑制规则配置，当存在与另一组匹配的警报（源）时，抑制规则将禁用与一组匹配的警报（目标）。
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
