<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>datasophon-plugins</artifactId>
        <groupId>com.datasophon</groupId>
        <version>${revision}</version>
    </parent>

    <artifactId>datasophon-plugins-impl</artifactId>
    <packaging>pom</packaging>
    <name>DataSophon Plugins Implementation</name>
    <description>DataSophon插件实现父模块</description>

    <modules>
        <module>core-plugins</module>
    </modules>

    <dependencies>
        <!-- 插件API -->
        <dependency>
            <groupId>com.datasophon</groupId>
            <artifactId>datasophon-plugin-api</artifactId>
        </dependency>
        
        <!-- PF4J -->
        <dependency>
            <groupId>org.pf4j</groupId>
            <artifactId>pf4j</artifactId>
        </dependency>
        
        <!-- SSH客户端 -->
        <dependency>
            <groupId>org.apache.sshd</groupId>
            <artifactId>sshd-core</artifactId>
        </dependency>
    </dependencies>

</project>