plugin.id=${plugin.id}
plugin.class=${plugin.class}
plugin.version=${plugin.version}
plugin.provider=${plugin.provider}
plugin.dependencies=${plugin.dependencies}
plugin.description=CPU utilization and load average checker plugin
plugin.license=Apache License 2.0
plugin.requires=*