# 1.Please provide the information of hosts needed to be inited in the format specified below
# 2.dataSophon.ip.i(eg:i=1,2,3.....):
# 3.dataSophon.password.i:
# 4.dataSophon.ssh.port.i:
# 5.dataSophon.ssh.port.hostname.i:
dataSophon.ip.1=192.168.6.121
dataSophon.password.1=Jd2019
dataSophon.ssh.port.1=22
dataSophon.ssh.port.hostname.1=ndp1

dataSophon.ip.2=192.168.6.122
dataSophon.password.2=Jd2019
dataSophon.ssh.port.2=22
dataSophon.ssh.port.hostname.2=ndp2

dataSophon.ip.3=192.168.6.123
dataSophon.password.3=Jd2019
dataSophon.ssh.port.3=22
dataSophon.ssh.port.hostname.3=ndp3

dataSophon.ip.4=192.168.6.124
dataSophon.password.4=Jd2019
dataSophon.ssh.port.4=22
dataSophon.ssh.port.hostname.4=ndp4

dataSophon.ip.5=192.168.6.125
dataSophon.password.5=Jd2019
dataSophon.ssh.port.5=22
dataSophon.ssh.port.hostname.5=ndp5

dataSophon.ip.6=192.168.6.126
dataSophon.password.6=Jd2019
dataSophon.ssh.port.6=22
dataSophon.ssh.port.hostname.6=ndp6

dataSophon.ip.7=192.168.6.127
dataSophon.password.7=Jd2019
dataSophon.ssh.port.7=22
dataSophon.ssh.port.hostname.7=ndp7

dataSophon.ip.8=192.168.1.115
dataSophon.password.8=Jd2019
dataSophon.ssh.port.8=22
dataSophon.ssh.port.hostname.8=ndp8

dataSophon.ip.9=192.168.1.116
dataSophon.password.9=Jd2019
dataSophon.ssh.port.9=22
dataSophon.ssh.port.hostname.9=ndp9

dataSophon.ip.10=192.168.1.117
dataSophon.password.10=Jd2019
dataSophon.ssh.port.10=22
dataSophon.ssh.port.hostname.10=ndp10