# 1.Please provide the information of hosts needed to be inited in the format specified below
# 2.dataSophon.ip.i(eg:i=1,2,3.....):
# 3.dataSophon.password.i:
# 4.dataSophon.ssh.port.i:
# 5.dataSophon.ssh.port.hostname.i:
dataSophon.ip.1=192.168.1.58
dataSophon.password.1=Jd2019
dataSophon.ssh.port.1=22
dataSophon.ssh.port.hostname.1=hadoop4

dataSophon.ip.2=192.168.1.59
dataSophon.password.2=Jd2019
dataSophon.ssh.port.2=22
dataSophon.ssh.port.hostname.2=hadoop5

