
# Whether to configure the local offline yum source true:need/false:needless
yum.repo.need=false
# Set the YUM source host IP
yum.repo.host.ip=192.168.6.121

#The Host information for installing the NMAP service
nmap.server.ip=192.168.6.121
nmap.server.port=22
nmap.server.password=Jd2019

# The Host information for installing the NTP service(Master)
ntp.master.ip=192.168.6.121

# Install MySQL machine node information
mysql.ip=192.168.6.121
mysql.host.ssh.port=22
mysql.host.ssh.password=Jd2019

# Set the MYSQL database login password
mysql.password=123456

# The total number of machines needed to be init.
init.host.num=10

# The total number of added machines needed to be init.
init.add.host.num=0

# Common Settings.
init.log.dir=./logs

# server operating system Settings : openEuler\centos8\arm
init.os=centos7



