plugin.id=system-info-collector
plugin.class=com.datasophon.plugins.systeminfo.SystemInfoCollectorPluginMain
plugin.version=1.0.0
plugin.provider=DataSophon Team
plugin.dependencies=
plugin.description=System information collector including OS and hardware info
plugin.license=Apache License 2.0
plugin.requires=*